config/routes.rb
require 'url_constrainer'

Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :confirmations => 'users/confirmations',
    :passwords => 'users/passwords'
  }

  devise_scope :user do
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end

  root 'static_pages#home'

  resources :goals do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:index, :create, :destroy]
  end

  constraints(UrlConstrainer.new) do
    resources :users, param: :username, only: [:show, :edit, :update, :destroy]
  end

  resources :users, only: [:index] do
    get :search, on: :collection
  end

  resources :users, only: [:show] do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
  end

  resources :notifications, only: [:index]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :login, :current_password

  mount_uploader :avatar, AvatarUploader
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :validatable, :confirmable, authentication_keys: [:login]

  has_many :goals, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_goals, through: :likes, source: :goal
  has_many :active_relationships, class_name: 'Relationship', foreign_key: :following_id, dependent: :destroy
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :following
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy,
                                  inverse_of: 'visitor'
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  validates :username, presence: true, namespace: true, uniqueness: true, length: { in: 4..20 },
                       format: { with: /\A[a-z0-9_]+\z/ }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, on: :create
  validates :profile, length: { maximum: 140 }

  def to_param
    username
  end

  # usernameとemailのどちらでもログイン可能
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).find_by(['lower(username) = :value OR lower(email) = :value',
                                      { value: login.downcase }])
    elsif conditions.key?(:username) || conditions.key?(:email)
      find_by(conditions.to_h)
    end
  end

  def already_liked?(goal)
    likes.exists?(goal_id: goal.id)
  end

  def like(goal)
    likes.create(goal_id: goal.id)
  end

  def unlike(goal)
    likes.find_by(goal_id: goal.id).destroy
  end

  def already_followed?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def follow(user)
    active_relationships.create(follower_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(follower_id: user.id).destroy
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and action = ? ', current_user.id, id, 'follow'])
    return unless temp.blank?

    notification = current_user.active_notifications.new(
      visited_id: id,
      action: 'follow'
    )
    notification.save if notification.valid?
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def update_resource(resource, params)
    return super if params['password']&.present?

    resource.update_without_password(params.except('current_password'))
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(_resource)
    "/users/#{current_user.username}"
  end

  # ユーザー情報の更新が成功した場合、リダイレクト先は編集ページのままにする。
  def after_update_path_for(_resource)
    edit_user_registration_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :admin_user, only: :destroy

  def index
    @search = User.ransack(params[:q])
    @users = @search.result
    @user = User.page(params[:page]).per(24)
  end

  def show
    @user = User.find_by!(username: params[:username])
    @users = User.where(username: params[:username])
    @goals = @user.goals.page(params[:page]).per(24)
    @likes = @user.like_goals.page(params[:page]).per(24)
  end

  def destroy
    User.find_by!(username: params[:username]).destroy
    flash[:success] = 'ユーザーは正常に削除されました。'
    redirect_to users_path
  end

  def followings
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/views/users/_search_form.html.erb
<div class="search-cover">
  <%= search_form_for search, class: "search" do |f| %>
    <%= f.hidden_field :username, class: "search-title" %>
    <%= f.search_field :username_cont, placeholder: "ユーザー名検索", class: "search-input" %>
    <%= f.submit "検索", class: "search-button" %>
  <% end %>
</div>

app/views/users/_show_goals.html.erb
<h3>目標件数：<%= @goals.count %></h3>

<% group.each do |goal| %>
  <div class="goal" id="goal">
    <%= link_to goal_path(goal) do %>
      <div class="goal-title">
        <%= goal.name unless goal.user.blank? %>
      </div>

      <div class="goal-content">
        <%= markdown(goal.description) %>
      </div>

      <% case goal.status %>
      <% when 0 then %>
        <span class="goal-status-not">未対応</span>
      <% when 1 then %>
        <span class="goal-status-process">処理中</span>
      <% when 2 then %>
        <span class="goal-status-processd">処理済み</span>
      <% when 3 then %>
        <span class="goal-status-done">完了</span>
      <% end %>
    <% end %>
  </div>
<% end %>

<div>
  <%= paginate group %>
  <div>
    <button>さらに表示</button>
  </div>
</div>

app/views/users/_show_likes.html.erb
<h3>いいね件数：<%= @likes.count %></h3>

<% group.each do |goal| %>
  <div class="goal" id="goal">
    <div class="goal-username">
      <%= link_to "@#{goal.user.username}", user_path(goal.user.username) unless goal.user.blank? %>
    </div>

    <%= link_to goal_path(goal) do %>
      <div class="goal-title">
        <%= goal.name %>
      </div>

      <div class="goal-content">
        <%= markdown(goal.description) %>
      </div>

      <% case goal.status %>
      <% when 0 then %>
        <span class="goal-status-not">未対応</span>
      <% when 1 then %>
        <span class="goal-status-process">処理中</span>
      <% when 2 then %>
        <span class="goal-status-processd">処理済み</span>
      <% when 3 then %>
        <span class="goal-status-done">完了</span>
      <% end %>
    <% end %>
  </div>
<% end %>

<div>
  <%= paginate group %>
  <div>
    <button>さらに表示</button>
  </div>
</div>

app/views/users/_user_cards.html.erb
<% group.each do |user| %>
  <div class="user">
    <!-- ユーザーカード：アバター -->
    <div class="user-image-cover">
      <% if user.avatar? %>
        <%= link_to image_tag(user.avatar.url, size: "200x200", alt: "avatar image", class: "user-image"), user_path(user) %>
      <% else %>
        <%= link_to image_tag("no_user.png", size: "200x200", alt: "avatar image", class: "user-image"), user_path(user) %>
      <% end %>
    </div>

    <!-- ユーザーカード：名前とユーザーネーム -->
    <div class="user-username">
      @<%= user.username %>
    </div>
  </div>
<% end %>

app/views/users/followers.html.erb
<h1>フォロワー：<%= @users.count %>人</h1>

<% if @users.empty? %>
  <p>フォローされていません</p>
<% end %>

<div class="follow-cover">
  <% @users.each do |user| %>
    <hr>
    <p><span>@</span><%= link_to user.username, user_path(user.username) %></p>

    <% if current_user != user %>
      <% if user.already_followed?(current_user) %>
        <p><%=link_to "フォロー中", user_relationships_path(user.id), method: :delete %></p>
      <% else %>
        <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/followings.html.erb
<h1>フォロー中：<%= @users.count %>人</h1>

<% if @users.empty? %>
  <p>フォローしているユーザーはいません</p>
<% end %>

<div class="follow-cover">
  <% @users.each do |user| %>
    <hr>
    <p><span>@</span><%= link_to user.username, user_path(user.username) %></p>

    <% if current_user != user %>
      <% if user.already_followed?(current_user) %>
        <p><%=link_to "フォロー中", user_relationships_path(user.id), method: :delete %></p>
      <% else %>
        <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/follows.html.erb
<h1>フォロー中：<%= @users.count %>人</h1>

<% if @users.empty? %>
  <p>フォローしているユーザーはいません</p>
<% end %>

<div class="follow-cover">
  <% @users.each do |user| %>
    <hr>
    <p><span>@</span><%= link_to user.username, user_path(user.username) %></p>

    <% if current_user != user %>
      <% if user.already_followed?(current_user) %>
        <p><%=link_to "フォロー中", user_relationships_path(user.id), method: :delete %></p>
      <% else %>
        <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/index.html.erb
<%= render 'search_form', search: @search %>

<div class="user-cover">
  <h2>ユーザー一覧</h2>
  <% provide(:title, 'すべてのユーザー') %>

  <%= render 'users/user_cards', group: @users %>

  <div>
    <%= paginate @user %>
    <div>
      <button>さらに表示</button>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="back-button-cover">
  <%= link_to users_path, class: "back-button" do %>
    <i class="fas fa-chevron-left"></i>
  <% end %>
</div>

<div class="user-show">
  <div class="user-show-header">
    <div class="user-show-header-head">
      <div class="user-show-image-cover">
        <%= image_tag(@user.avatar.url, size: "68x68", alt: "avatar image", class: "user-show-image") %>
      </div>

      <% if user_signed_in? %>
          <% if @user == current_user %>
            <div class="user-show-logoutbutton-cover">
              <%= button_to "プロフィール編集", edit_user_registration_path, method: :get, class: "user-show-editbutton" %>
              <%= button_to "ログアウト", destroy_user_session_path, method: :delete, class: "user-show-logoutbutton" %>
            </div>
          <% elsif @user.guest? %>
            <!-- なにも表示しない -->
          <% end %>
      <% end %>
    </div>

    <div>@<%= @user.username %></div>
    <div><%= @user.profile %></div>

    <% if user_signed_in? %>
      <div>
        <%=link_to "フォロー", followings_user_path(@user.id) %>
        <%=link_to "フォロワー", followers_user_path(@user.id) %>
      </div>

      <div class="user-show-followbutton-cover">
        <% @users.each do |user| %>
          <% if current_user != user %>
            <% if user.already_followed?(current_user) %>
              <%=button_to "フォロー中", user_relationships_path(user.id), method: :delete, class: "user-show-followbutton is-active" %>
            <% else %>
              <%=button_to "フォローする", user_relationships_path(user.id), method: :goal, class: "user-show-followbutton" %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="user-show-body">
    <ul class="user-show-tabs js-tab">
      <li class="active-goals active">目標</li>
      <li class="active-likes" id="like">いいね</li>
    </ul>

    <ul class="user-show-tabContents js-tabContents">
      <li class="active">
        <% if @user.goals.any? %>
          <%= render 'show_goals', group: @goals %>
        <% else %>
          <div>投稿がありません</div>
        <% end %>
      </li>

      <li>
        <% if @user.likes.any? %>
          <%= render 'show_likes', group: @likes %>
        <% else %>
          <div>"いいね！" した投稿がありません</div>
        <% end %>
      </li>
    </ul>
  </div>

  <% if user_signed_in? %>
    <% if @user == current_user %>
      <!-- なにも表示しない -->
    <% elsif @user.guest? %>
      <!-- なにも表示しない -->
    <% elsif current_user.admin? %>
      <div class="user-deletebutton-cover">
        <%= link_to "このユーザーを削除する", @user, method: :delete, data: {confirm: "このユーザーを削除してもよろしいですか?"}, class: "user-deletebutton" %>
      </div>
    <% end %>
  <% end %>
</div>