config/routes.rb
require 'url_constrainer'

Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :confirmations => 'users/confirmations',
    :passwords => 'users/passwords'
  }

  devise_scope :user do
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end

  root 'static_pages#home'

  resources :goals do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:index, :create, :destroy]
  end

  constraints(UrlConstrainer.new) do
    resources :users, param: :username, only: [:show, :edit, :update, :destroy]
  end

  resources :users, only: [:index] do
    get :search, on: :collection
  end

  resources :users, only: [:show] do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
  end

  resources :notifications, only: [:index]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/goal.rb
class Goal < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  before_create :set_untitled

  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :notifications, dependent: :destroy

  validates :description, length: { maximum: 240 }
  validates :user_id, presence: true

  # いいね通知
  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(['visitor_id = ? and visited_id = ? and goal_id = ? and action = ? ', current_user.id,
                               user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    return unless temp.blank?

    notification = current_user.active_notifications.new(
      goal_id: id,
      visited_id: user_id,
      action: 'like'
    )
    # 自分の投稿に対するいいねの場合は、通知済みとする
    notification.checked = true if notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
  end

  # コメント通知
  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(goal_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      goal_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    notification.checked = true if notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
  end

  private

  def set_untitled
    self.name = '無題' if name.blank?
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def index
    @search = Goal.ransack(params[:q])
    @goals = @search.result
  end

  def show
    @goal = Goal.find(params[:id])
    @comment = @goal.comments.build
    @comments = @goal.comments
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    @goal.save

    if @goal.save
      flash[:success] = '投稿が送信されました。'
      redirect_to user_path(current_user)
    else
      render 'goals/new'
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])

    if @goal.update(goal_params)
      flash[:success] = '投稿が更新されました。'
      redirect_to @goal
    else
      render 'edit'
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy

    flash[:success] = '投稿は正常に削除されました。'
    redirect_to goals_path
  end

  private

  def goal_params
    params.require(:goal).permit(:name, :description, :status)
  end
end

app/views/goals/_comment.html.erb
<% if user_signed_in? %>
  <%= form_with(model:[@goal, @comment], local: true, class: "comment-form js-modal") do |f| %>
    <div class="comment-modalOff-cover">
      <span class="comment-modalOff js-modalOff">✖︎<span>
    </div>

    <%= f.text_area :content, placeholder: "内容を入力してください" %>
    <br>
    <div class="comment-button-cover">
      <%= f.submit 'コメントする', class: "comment-button" %>
    </div>
  <% end %>

    <% if comments.any? %>
      <% comments.each do |comment| %>
        <div class="comment">
          <div class="comment-username">
            <%= link_to "@#{comment.user.username}", user_path(comment.user.username) unless comment.user.blank? %>
          </div>

          <div class="comment-content">
            <%= comment.content %>
          </div>

          <div class="comment-createdAt">
            <%= comment.created_at %>
          </div>

          <div class="comment-deleteButton-cover">
            <% if comment.user == current_user %>
              <%= link_to "削除", goal_comment_path(@goal, comment), method: :delete, data: { confirm: "コメントを削除しますか？" }, class: "comment-deleteButton" %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <div>まだコメントがありません。</div>
    <% end %>
<% end %>

app/views/goals/_form.html.erb
<%= form_with(model: @goal, local: true, class: "goal-form") do |form| %>
  <div class="goal-form-title">
    <%= form.hidden_field :name %>
    <%= form.text_field :name, placeholder: "題名" %>
  </div>

  <div class="goal-form-content">
    <%= form.hidden_field :description %>
    <%= form.text_area :description, placeholder: "内容" %>
  </div>

  <div class="goal-form-status">
    <%= form.label :status, "状態" %>
    <%= form.select :status, [['未対応',0],['処理中',1],['処理済み',2],['完了',3]] %>
  </div>

  <div class="goal-form-button-cover">
    <%= form.submit "登録", class: "goal-form-button" %>
  </div>
<% end %>

app/views/goals/_likes.html.erb
<% if user_signed_in? %>
  <% if current_user.already_liked?(goal) %>
    <% if goal.user != current_user %>
      <%= link_to 'いいねを取り消す', goal_like_path(goal), method: :delete, class: "liked-button" %>
    <% end %>
  <% else %>
    <% if goal.user != current_user %>
      <%= link_to 'いいね', goal_likes_path(goal), method: :post %>
    <% end %>
  <% end %>
<% end %>

app/views/goals/_search_form.html.erb
<div class="search-cover">
  <%= search_form_for search, class: "search" do |f| %>
    <%= f.hidden_field :name, class: "search-title" %>
    <%= f.search_field :name_or_description_cont, placeholder: "タイトル/内容検索", class: "search-input" %>
    <%= f.submit "検索", class: "search-button" %>
  <% end %>
</div>

app/views/goals/edit.html.erb
<h2>目標の編集</h2>

<%= render 'form' %>

app/views/goals/index.html.erb
<%= render 'search_form', search: @search %>

<% if user_signed_in? %>
  <%= link_to new_goal_path do %>
    <div class="goal-addbutton" id="goal-addbutton">
      <i class="fas fa-plus"></i>
    </div>
  <% end %>
<% end %>

<% @goals.each do |goal| %>
  <div class="goal" id="goal">
    <div class="goal-username">
      <%= link_to "@#{goal.user.username}", user_path(goal.user.username) unless goal.user.blank? %>
    </div>

    <%= link_to goal_path(goal) do %>
      <div class="goal-title">
        <%= goal.name %>
      </div>

      <div class="goal-content">
        <%= markdown(goal.description) %>
      </div>

      <% case goal.status %>
      <% when 0 then %>
        <span class="goal-status-not">未対応</span>
      <% when 1 then %>
        <span class="goal-status-process">処理中</span>
      <% when 2 then %>
        <span class="goal-status-processd">処理済み</span>
      <% when 3 then %>
        <span class="goal-status-done">完了</span>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/goals/new.html.erb
<h2>目標の追加</h2>

<%= render 'form' %>

app/views/goals/show.html.erb
<% if user_signed_in? %>
  <div class="modal-bg js-modalBg" data-keyboard="false" data-backdrop="static"></div>
<% end %>

<div class="back-button-cover">
  <%= link_to goals_path, class: "back-button" do %>
    <i class="fas fa-chevron-left"></i>
  <% end %>
</div>

<div class="goal" id="goal">
  <div class="goal-username">
    @<%= link_to @goal.user.username, user_path(@goal.user.username) unless @goal.user.blank? %>
  </div>

  <div class="goal-inner">
    <div class="goal-title">
      <%= @goal.name %>
    </div>

    <div class="goal-content">
      <%= markdown(@goal.description) %>
    </div>

    <% case @goal.status %>
    <% when 0 then %>
      <span class="goal-status-not">未対応</span>
    <% when 1 then %>
      <span class="goal-status-process">処理中</span>
    <% when 2 then %>
      <span class="goal-status-processd">処理済み</span>
    <% when 3 then %>
      <span class="goal-status-done">完了</span>
    <% end %>

    <% if @goal.user == current_user %>
      <div class="goal-button-cover">
        <%= link_to '編集', edit_goal_path(@goal), class: "goal-button-edit" %>
        <%= link_to '削除', goal_path(@goal), method: :delete, data: { confirm: '投稿を削除しますか？' }, class: "goal-button-delete" %>
      </div>
    <% end %>

    <div class="goal-footer">
      <div class="goal-footer-head">
        <% if @comments.any? %>
          <span>
            コメント件数：<%= @comments.count %>
          </span>
        <% end %>
        <span class="goal-count">
          <%= link_to "いいね件数", goal_likes_path(@goal) %>：<%= @goal.likes.count %>
        </span>
      </div>

      <ul class="goal-footer-body">
        <% if user_signed_in? %>
          <li class="active-comment js-modalOn" id="comment">コメント</li>
        <% else %>
          <li class="active-comment comment-toolTip" id="comment" data-tooltip="ログイン後に利用できます。">コメント</li>
        <% end %>
        <li class="active-like">
          <%= render 'likes', goal: @goal %>
        </li>
      </ul>

      <div class="goal-footer-foot">
        <%= render 'comment', comments: @comments %>
      </div>
    </div>
  </div>
</div>