config/routes.rb
require 'url_constrainer'

Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :confirmations => 'users/confirmations',
    :passwords => 'users/passwords'
  }

  devise_scope :user do
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end

  root 'static_pages#home'

  resources :goals do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:index, :create, :destroy]
  end

  constraints(UrlConstrainer.new) do
    resources :users, param: :username, only: [:show, :edit, :update, :destroy]
  end

  resources :users, only: [:index] do
    get :search, on: :collection
  end

  resources :users, only: [:show] do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
  end

  resources :notifications, only: [:index]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="notice-cover">
    <%= content_tag(:div, value, class: "#{key}") %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p class="copyright">© Copyright 2020. All rights reserved.</p>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <h1 class="header-logo">
    <%= link_to website_name, root_path %>
  </h1>
  <nav class="nav-cover">
    <ul class="nav">
      <li class="nav-item">
        <%= link_to goals_path do %>
          <i class="fas fa-tasks fa-2x"></i>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to users_path do %>
          <i class="fas fa-users fa-2x"></i>
        <% end %>
      </li>
      <% if user_signed_in? && current_user.admin? %>
        <li class="nav-item">
          <%= link_to user_path(current_user) do %>
            <i class="fas fa-user fa-2x"></i>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to notifications_path do %>
            <i class="fa fa-bell fa-2x"></i>
          <% end %>
        </li>
      <% elsif user_signed_in? %>
        <li class="nav-item">
          <%= link_to user_path(current_user) do %>
            <i class="fas fa-user fa-2x"></i>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to notifications_path do %>
            <i class="fa fa-bell fa-2x"></i>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "ログイン", new_user_session_path %>
        </li>
        <li class="nav-item">
          <%= link_to "新規登録", new_user_registration_path %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_signin_as_guest.html.erb
<div class="modal-bg js-modalBg" data-keyboard="false" data-backdrop="static"></div>

<div class="guest-login-cover">
  <div class="guest-login-link-cover js-modalOn">
    <div class="guest-login-link">すぐに全機能をお試しになりたい場合は、<div id="guest_login">こちらからゲストユーザーとしてログインできます。</div></div>
  </div>

  <div class="guest-login-modal js-modal">
    <div class="guest-login-modal-header">
      ゲストユーザーとしてログインしますか？
    </div>
    <div class="guest-login-modal-footer">
      <button class="guest-login-cancel-button js-modalOff">キャンセル</button>

      <%= form_for(User.new, as: :user, url: session_path(:user)) do |f| %>
        <%= f.hidden_field :login, value: "guest" %>
        <%= f.hidden_field :password, value: "123456" %>
        <%= f.submit "ゲストログイン", class: "guest-login-button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCatchup</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="content-language" content="ja" charset="utf-8">
  </head>

  <body class="js-body">
    <% unless user_signed_in? %>
      <%= render 'layouts/signin_as_guest' %>
    <% end %>

    <div class="container js-container">
      <%= render 'layouts/header' %>
      <%= render 'layouts/flash_messages' %>

      <% unless current_page?(root_path) %>
        <main class="main-loggedIn">
          <%= yield %>
        </main>
      <% else %>
        <main class="main-notLoggedIn">
          <%= yield %>
        </main>
      <% end %>
    </div>
  </body>
</html>